apiVersion: v1
kind: Service
metadata:
  name: miniapp-flask
  labels:
    app: miniapp-flask
spec:
  ports:
    - port: 5555
      protocol: TCP
      targetPort: 5555
  selector:
    app: miniapp-flask
  type: LoadBalancer
  loadBalancerIP: 34.84.188.30